version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway

  user-service:
    build: ./services/user-service
    container_name: user-service

  bus-service:
    build: ./services/bus-service
    container_name: bus-service

  car-service:
    build: ./services/car-service
    container_name: car-service

  train-service:
    build: ./services/train-service
    container_name: train-service

  flight-service:
    build: ./services/flight-service
    container_name: flight-service

  partner-service:
    build: ./services/partner-service
    container_name: partner-service

  booking-service:
    build: ./services/booking-service
    container_name: booking-service

  partnership-client:
    build: ./clients/partnership-client
    container_name: partnership-client

  guest-client:
    build: ./clients/guest-client
    container_name: guest-client

  administration-client:
    build: ./clients/administration-client
    container_name: administration-client

  mssql:
    build: ./mssql
    container_name: mssql

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
